// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: surveymarkup.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateMarkupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId    int32   `protobuf:"varint,1,opt,name=unitId,proto3" json:"unitId,omitempty"`
	SurveyIds []int32 `protobuf:"varint,2,rep,packed,name=surveyIds,proto3" json:"surveyIds,omitempty"`
	Language  string  `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *GenerateMarkupRequest) Reset() {
	*x = GenerateMarkupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_surveymarkup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMarkupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMarkupRequest) ProtoMessage() {}

func (x *GenerateMarkupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surveymarkup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMarkupRequest.ProtoReflect.Descriptor instead.
func (*GenerateMarkupRequest) Descriptor() ([]byte, []int) {
	return file_surveymarkup_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateMarkupRequest) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *GenerateMarkupRequest) GetSurveyIds() []int32 {
	if x != nil {
		return x.SurveyIds
	}
	return nil
}

func (x *GenerateMarkupRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GenerateMarkupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Markup string `protobuf:"bytes,1,opt,name=markup,proto3" json:"markup,omitempty"`
}

func (x *GenerateMarkupResponse) Reset() {
	*x = GenerateMarkupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_surveymarkup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMarkupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMarkupResponse) ProtoMessage() {}

func (x *GenerateMarkupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surveymarkup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMarkupResponse.ProtoReflect.Descriptor instead.
func (*GenerateMarkupResponse) Descriptor() ([]byte, []int) {
	return file_surveymarkup_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateMarkupResponse) GetMarkup() string {
	if x != nil {
		return x.Markup
	}
	return ""
}

var File_surveymarkup_proto protoreflect.FileDescriptor

var file_surveymarkup_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x69, 0x0a, 0x15, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x09, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x49, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x32, 0x68, 0x0a, 0x15, 0x53, 0x75, 0x72, 0x76,
	0x65, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72,
	0x6b, 0x75, 0x70, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x73, 0x75,
	0x72, 0x76, 0x65, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x6d, 0x61,
	0x72, 0x6b, 0x75, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_surveymarkup_proto_rawDescOnce sync.Once
	file_surveymarkup_proto_rawDescData = file_surveymarkup_proto_rawDesc
)

func file_surveymarkup_proto_rawDescGZIP() []byte {
	file_surveymarkup_proto_rawDescOnce.Do(func() {
		file_surveymarkup_proto_rawDescData = protoimpl.X.CompressGZIP(file_surveymarkup_proto_rawDescData)
	})
	return file_surveymarkup_proto_rawDescData
}

var file_surveymarkup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_surveymarkup_proto_goTypes = []interface{}{
	(*GenerateMarkupRequest)(nil),  // 0: model.GenerateMarkupRequest
	(*GenerateMarkupResponse)(nil), // 1: model.GenerateMarkupResponse
}
var file_surveymarkup_proto_depIdxs = []int32{
	0, // 0: model.SurveyMarkupGenerator.GenerateMarkup:input_type -> model.GenerateMarkupRequest
	1, // 1: model.SurveyMarkupGenerator.GenerateMarkup:output_type -> model.GenerateMarkupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_surveymarkup_proto_init() }
func file_surveymarkup_proto_init() {
	if File_surveymarkup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_surveymarkup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMarkupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_surveymarkup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMarkupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_surveymarkup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_surveymarkup_proto_goTypes,
		DependencyIndexes: file_surveymarkup_proto_depIdxs,
		MessageInfos:      file_surveymarkup_proto_msgTypes,
	}.Build()
	File_surveymarkup_proto = out.File
	file_surveymarkup_proto_rawDesc = nil
	file_surveymarkup_proto_goTypes = nil
	file_surveymarkup_proto_depIdxs = nil
}
